### ISSUE TITLE
Tablet support

### ISSUE THREAD

**Issue by Matthias84** [tardypad/sailfishos-daily-comics#26]
While everybody is waiting for the tablet, it might be nice, if DC could be compiled and packaged for x86 as well? https://lists.sailfishos.org/pipermail/devel/2015-September/006512.html

**Comment by tardypad** [comment]
It doesn't make much sense to me to just package the app for tablet without testing it and adapting the layout
And I haven't ordered the tablet and I don't plan to do so.
So unless someone with a tablet do the work, this won't happen I'm afraid :-(

**Comment by Matthias84** [comment]
But the mail says, that the tablet can be emulated?

**Comment by benaryorg** [comment]
I did receive my tablet yesterday and, as I love al the comics and think that your app is great, will test the app as soon as I find the time which is this week already I hope.

**Comment by a-dekker** [comment]
I have been running Daily-comics on the tablet for quite some time now. For starters it is great to read comics in the tablets screen size. On the Jolla phone it sometimes looks a bit tiny. And everything scales very well already, there is no real need to change anything in the layout.

**Comment by LouisDK1** [comment]
@a-dekker
Do you have an rpm file to share? :)

**Comment by a-dekker** [comment]
It is not the most recent version, but here it is: https://dl.dropboxusercontent.com/u/42147901/harbour-dailycomics-1.5.5-1.i486.rpm

**Comment by tardypad** [comment]
I've made a build for the tablet which is available on the OpenRepos page
https://openrepos.net/content/tardypad/daily-comics
Thanks to @cnlpete, it contains some basic layout changes #29

I am not sure if the build is made correctly as I can't test it myself.
So please check it and let me know if anything is wrong.
Thanks!

**Comment by benaryorg** [comment]
I've tested right now and it seems to work fine.

Thank you for making this happen!

**Comment by tardypad** [comment]
Cool! Thanks for checking.

**Comment by benaryorg** [comment]
Ah, sorry, there's one thing. It took me a while to see it and it's very hard to capture in a screenshot and it happens rarely, so it would be nice if someone could confirm that.

If the comics are loading/checking for updates there's this progress bar on the bottom of the screen, I was holding the tablet in portrait mode (don't know if other orientations act similar) and the text was about 3 pixels out of the screen, to the bottom.

**Comment by benaryorg** [comment]
Okay, I got to see it again. All orientations have the text go out on the bottom a few pixels and on the right the word "New" was also overflowing to the right.

**Comment by cnlpete** [comment]
I can confirm this, apparently missed this during my quick tests.
The lower updating bar seems to have wrong dimensions. I will try to look into this and produce a fix. Maybe this coming weekend =)

@tardypad If you want you can reopen this and assign me or add a new ticket.
