### ISSUE TITLE
Add reset action in settings

### ISSUE THREAD

**Issue by tardypad** [tardypad/sailfishos-daily-comics#53]
In the Settings page, one can sometimes accidentally use the "select all" or "clear all" action and thus lose the complete list of his favorites.
It would be nice to have a reset action getting displayed in the menu once there is some modication done in the list. This way such mistakes can be easily reverted without having to go back through the whole list and selecting again each favorite comic.

**Comment by Maledictus** [comment]
We can make settings page as dialog and doesn't save selected comics until Accept dialog action will chose.
What do you think about this?

**Comment by tardypad** [comment]
Your idea sounds to be a better solution to the problem I described in this issue :)
I don't recall if there was any reason I made the settings page the way it is, without using a dialog.
So I guess, you can go for it
