### ISSUE TITLE
Favorite strips

### ISSUE THREAD

**Issue by tardypad** [tardypad/sailfishos-daily-comics#6]
Add the possibility to favorite strips and save them locally, so they can be easily viewed later

**Comment by Maledictus** [comment]
May be will be enough to add possibility to save comics in gallery?

**Comment by tardypad** [comment]
I think that's a good simpler idea.
Then there wouldn't be the need to add a lot of new UI to list, view and manage them, that would all be done within the Gallery. The Gallery features are limited but it should be good enough at first I think.

I don't know the possibility of the gallery but if possible it would be nice to put them in a separate folder and maybe then they can appear as a separate group in the Gallery (like screenshots have their own "group")

**Comment by Maledictus** [comment]
So, I have done this but there is no separate menu in gallery for my directory and all comics visible in main Photo section but files are in daily comics directory
