### ISSUE TITLE
Comics Kingdom spoils the fun

### ISSUE THREAD

**Issue by cow-n-berg** [tardypad/sailfishos-daily-comics#79]
Beetle Bailey and Hagar the Horrible are broken, after moving to Comics Kingdom.

The new RegEx for both would be:    var regex = /image-url="(.*img.php[^"]*)"/;
but then the app says "Saving error, Can't save comic" probably because it doesn't know to expect a png file.

**Comment by Maledictus** [comment]
Fixed
