### ISSUE TITLE
Swamp has changed, new regex here

### ISSUE THREAD

**Issue by cow-n-berg** [tardypad/sailfishos-daily-comics#88]
var regex = /\n.*\n.*<img[^>]*src="([^"]*)"/;

**Comment by cow-n-berg** [comment]
Or maybe /<img[^>]*src="([^"]*)"\s*alt="Swamp\sCartoon\sof\sthe\sDay/

**Comment by dryo** [comment]
@cow-n-berg Your regex does not match for me. At least a plus sign has to be added, like so:
` 
<img[^>]src="([^"]+)"\s*alt="Swamp\sCartoon\sof\sthe\sDay
`
To make it even more general I'd propose this one:
`
<img[^>]+src="([^"]+)"[^>]+alt="Swamp\s+Cartoon\s+of\s+the\s+Day
`
I made pull request #92.
