### ISSUE TITLE
Broken comics

### ISSUE THREAD

**Issue by Maledictus** [tardypad/sailfishos-daily-comics#90]
"Truth Facts"
 "The Adventures of Business Cat" - expired certificate
"Safely Endangered" - moved to https://www.webtoons.com/en/comedy/safely-endangered/list?title_no=352 and now splitting in some images
"Einbilder" - fixed
"Dennis The Menace" - works
"Beetle Bailey" - works

**Comment by cow-n-berg** [comment]
CommitStrip has changed the website. Is there a way to:
1. use a RegEx to find the page, the
2. load that page and perform a 2nd RegEx?

Any ideas?

**Comment by cow-n-berg** [comment]
Right. Tried one more thing, and it worked for Lectrr. I used /s at the end to search across new lines. Does not seem to work in all RegEx varieties, but it works here. \o/
var regex = /class="image">.*class="image">.*class="image"><img[^>]*src="([^"]*)"/s;

**Comment by cow-n-berg** [comment]
I tried the following, but it did not work:

function(page) {
    var regex1 = /<a href="(http:\/\/www.commitstrip.com\/en\/20[^"]*)"/;
    var match1 = regex1.exec(page);
	var newpage = match1[1];
    var regex2 = /<p><img[^>]*src="([^"]*)"/;
    var match2 = regex2.exec(newpage);
    return match2[1];
}

**Comment by Maledictus** [comment]
Bro, thank you for your efforts but I @tardypad doesn't unswer and I can't make a new release with fixes

**Comment by Maledictus** [comment]
CommitStrip works fine without changes.
